### ISSUE TITLE
在主播下播的时候，状态应该是从status 1->0,但是它还是会提示一次开播了。

### ISSUE THREAD

**Issue by zy8466** [ly123567/CQP-LiveSignForDouyu#2]
在主播下播的时候，状态应该是从status 1->0,但是它还是会提示一次开播了。

**Comment by ly123567** [comment]
有一部分主播使用的是第三方的直播软件，这类直播软件可能会因为自身运行机制、或者主播的误操作造成再次开播的情况，插件一律是以Douyu提供API为准的。
如果仍有问题欢迎继续反馈~
